# Generated by Django 5.0.4 on 2024-11-21 02:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('branch_id', models.IntegerField(primary_key=True, serialize=False)),
                ('branch_number', models.IntegerField()),
                ('branch_name', models.TextField()),
                ('branch_adress_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('customer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_name', models.TextField()),
                ('customer_surname', models.TextField()),
                ('customer_dni', models.IntegerField()),
                ('dob', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.sucursal')),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('account_id', models.IntegerField(primary_key=True, serialize=False)),
                ('balance', models.IntegerField()),
                ('iban', models.TextField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('loan_id', models.IntegerField(primary_key=True, serialize=False)),
                ('loan_type', models.TextField()),
                ('loan_date', models.DateField()),
                ('loan_total', models.PositiveIntegerField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('employee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('employee_name', models.TextField()),
                ('employee_surname', models.TextField()),
                ('employee_hire_date', models.DateField()),
                ('employee_DNI', models.PositiveIntegerField()),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.sucursal')),
            ],
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField(max_length=20)),
                ('cvv', models.IntegerField(max_length=3)),
                ('fecha_otorgamiento', models.DateField()),
                ('fecha_expiracion', models.DateField()),
                ('tipo', models.TextField()),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.cliente')),
                ('marca_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.marca')),
            ],
        ),
    ]
