# Generated by Django 5.0.4 on 2024-11-25 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0007_alter_tarjeta_marca_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
