# Generated by Django 5.0.4 on 2024-11-28 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0011_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='dni',
            field=models.CharField(default=44316209, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
