# Generated by Django 5.0.4 on 2024-11-21 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_alter_cliente_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loans.marca'),
        ),
    ]
